# Generated by Django 4.0.4 on 2022-05-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complete_Url', models.CharField(max_length=100)),
                ('Shorten_Url', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
